import Head from 'next/head';
import Homepage from './Homepage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflouix</title>
        <meta name="Netflouix" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Homepage />
    </>
  );
}
