import { Navbar } from '@/components/Navbar';
import Head from 'next/head';
import { Main } from '@/components/Main';

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix clone</title>
        <meta name="NetflixClone" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Navbar />
    </>
  );
}
